language: python

sudo: required
services:
  - docker
env:
  global:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
matrix:
  include:
    - python: "2.7"
      env: PYVER=cp27-cp27m
    - python: "3.4"
      env: PYVER=cp34-cp34m
    - python: "3.5"
      env: PYVER=cp35-cp35m
    - python: "3.6"
      env: PYVER=cp36-cp36m
    - python: "3.7-dev"
      env: PYVER=cp37-cp37m

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PYVER -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
  # According to https://github.com/travis-ci/dpl/issues/496, copying files to dist/ is enough to get them uploaded
  - mkdir -p dist/
  - cp wheelhouse/qcorex-*.whl dist/

deploy:
  provider: pypi
  user: JelleZijlstra
  password:
    secure: MBUgREEJH4RfPBrV9ijX6XINg3wIkphPvDqzadx+esFCjTfBRNdaL4Owx+cS/dH8DXSJLCet77I4lrn+trFIjh2sQXte4Q5pJnUxzcZmqp39vKukcID2LtOcwsiTk9a5EJeEAVJw+Z6XXTUrXqlKzGKj9ijxR/KfbeIKCAiRbMUC5QSjZhGs3JRGIAMnNTGatwg7L75cy0Gh1YsImDxhyncHJPRJwKdsNMR4Zg/pdjvfboqr88/jP7/bdEj5dyjaFrMwX/yv8l2yZHUjpKT9TaG3Z6I8UA6oZ7Tv/B+zvghVVX/Myyi+9Qcu9iVcFZ4WzX460Gbr3ja5t95p4i/JoSOw1vW4O6lLO5tjFkOY5tgcy3jocv7qPDJRbohzRXhtJjiJB9x+de68szKUAtyY/kVn0JKlVUtSwgswG7F50tCZPrtqLtdGcV2dLuCk1Ofej0uD/0/qAIpMlQrCURKaIEm6dKD/L+AOHulBinFXsbZV7ZUFl/WEU34/IIeGjCOJQwTteS0DF5e8rZq7d+urbaXSGXkdf7Cx3iruG8Dv5zUKcFbVm05Ibh2VuhvBBCc9TNhtb3+aGGDB3xnr0OnB9xor2POtVW0lT7hx/dDqwCE+ip4cbCy2UDI62Dv/nVv1Fqhgk3Lz+CUtD/kGsooMGToVVC9FzKoedanKXZdbtPE=
  on:
    tags: true
    branch: testpypi
  skip_cleanup: true
  distributions: sdist
  server: https://test.pypi.org/legacy/
